# Generated by Django 4.0 on 2022-01-06 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_blogpost_own'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='own',
            new_name='owner',
        ),
    ]
